accounts/urls.py
from django.conf.urls import url, patterns
from .views import persona_login
from django.contrib.auth.views import logout

urlpatterns = patterns(
    '',
    url(r'^login$', persona_login, name='persona_login',),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout',),
)

lists/urls.py
from django.conf.urls import patterns, url
from .views import new_list, view_list, my_lists, share_list

urlpatterns = patterns(
    '',
    url(r'^(?P<pk>\d+)/$', view_list, name='view_list'),
    url(r'^(?P<pk>\d+)/share/$', share_list, name='share_list'),
    url(r'^new$', new_list, name='new_list'),
    url(r'^users/(?P<email>.+)/$', my_lists, name='my_lists'),
)

superlists/urls.py
from django.conf.urls import patterns, url, include
# from django.contrib import admin


urlpatterns = patterns(
    '',
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^lists/', include('lists.urls')),
    url(r'^accounts/', include('accounts.urls')),
    # url(r'^admin/', include(admin.site.urls)),
)

accounts/models.py
from django.db import models
from django.utils import timezone


class User(models.Model):
    email = models.EmailField(primary_key=True)
    last_login = models.DateTimeField(default=timezone.now)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    def is_authenticated(self):
        return True

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

class List(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
    )
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='shared_lists',
    )

    @property
    def name(self):
        if self.item_set:
            return self.item_set.first().text
        else:
            return 'empty list {pk}'.format(self.pk)

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    def share(self, email):
        User = get_user_model()
        recipient, _ = User.objects.get_or_create(email=email)
        self.shared_with.add(recipient)


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

lists/forms.py
from django import forms
from .models import Item
from django.core.exceptions import ValidationError

EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):

    # def save(self, for_list):
    #     self.instance.list = for_list
    #     return super().save()

    class Meta:
        model = Item
        fields = ('text',)

        widgets = {
            'text': forms.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR}
        }


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

class NewListForm:
    pass

accounts/views.py
import sys
from django.contrib.auth import authenticate, login
# from django.shortcuts import redirect
from django.http import HttpResponse

def persona_login(request):
    user = authenticate(assertion=request.POST.get('assertion'))
    if user:
        login(request, user)
    return HttpResponse('OK')

# def login(request):
#     print('login view', file=sys.stderr)
#     assertion = request.POST['assertion']
#     # user = PersonaAuthenticationBackend().authenticate(assertion)
#     user = authenticate(assertion=assertion)
#     if user is not None:
#         auth_login(request, user)
#     return redirect('/')

# def logout(request):
#     auth_logout(request)
#     return redirect('/')

lists/views.py
""" Views of list app. Visitors can view and create lists and listitems. """
from django.shortcuts import render, redirect
from .models import List
from .forms import ItemForm, ExistingListItemForm, NewListForm
from django.contrib.auth import get_user_model
User = get_user_model()

def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})

def view_list(request, pk):
    list_ = List.objects.get(id=pk)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, 'form': form, })

def share_list(request, pk):
    list_ = List.objects.get(id=pk)
    if request.method == 'POST':
        email = request.POST['email']
        list_.share(email)
    return redirect(list_)

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List()
        if request.user.is_authenticated():
            list_.owner = request.user
        list_.save()
        form.instance.list = list_
        form.save()
        return redirect(list_)
    else:
        return render(request, 'home.html', {'form': form})

def new_list2(request):
    NewListForm(data=request.POST)

def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<html
lang="en">
<head>
	<title>{% block title %}To-Do lists{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/base.css" rel="stylesheet" media="screen">
    <link href="/static/favicon.ico" rel="shortcut icon">
</head>
<body>
	<div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <a href="/" class="navbar-brand">Superlists</a>
      {% if user.email %}
        <ul class="nav navbar-nav">
          <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
        </ul>
        <a href="{% url 'logout' %}" class="btn navbar-brn navbar-right" id="id_logout">Log out</a>
        <span class="navbar-text navbar-right">Logged in as {{ user.email }}</span>
      {% else %}
        <a href="#" class="btn navbar-brn navbar-right" id="id_login">Sign in</a>
      {% endif %}
    </nav>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 jumbotron">
				<div class="text-center">
					<h1>{% block header_text %}{% endblock %}</h1>

          {% block list_form %}
            <form method="POST" action="{% block form_action %}{% endblock %}">
              {% csrf_token %}
              {{ form.text }}
              {% if form.errors %}
                <div class="form-group has-error">
                  <span class="help-block">{{ form.text.errors }}</span>
                </div>
              {% endif %}
            </form>
          {% endblock list_form %}

				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				{% block table %}
				{% endblock table %}
			</div>
		</div>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        {% block extra_content %}
        {% endblock extra_content %}
      </div>
    </div>
	</div>
  <script src="http://code.jquery.com/jquery.min.js"></script>
  <script src="http://login.persona.org/include.js"></script>
  <script src="/static/js/list.js"></script>
  <script src="/static/js/accounts.js"></script>
  <script>
    $(document).ready(function(){
      var user = "{{ user.email }}" || null;
      var token = "{{ csrf_token }}";
      var urls = {
        login: "{% url 'persona_login' %}",
        logout: "{% url 'logout' %}"
      };
      Superlists.Accounts.initialize(navigator, user, token, urls);
    });
  </script>

</body>
</html>

lists/templates/home.html
{% extends "base.html" %}
{% block header_text %}Start a new To-Do lists{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends "base.html" %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}
{% block table %}
	<table id="id_list_table" class="table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
  </table>
{% endblock table %}
{% block extra_content %}
  <div class="row">
    <div class="col-md-6">
      {% if list.owner != user %}
        <h2>List owner</h2>
        <p id="id_list_owner">{{ list.owner.email }}</p>
      {% else %}
        {% if list.shared_with.all %}
          <h2>List shared with</h2>
          <ul>
            {% for sharee in list.shared_with.all %}
              <li class="list-sharee">{{ sharee.email }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      {% endif %}
    </div>
    <div class="col-md-6">
      <h2>Share this list</h2>
      <form method="POST" action="/lists/{{ list.id }}/share/" id="share-list">
        {% csrf_token %}
        <input required type="email" name="email" placeholder="your-friend@example.com">
      </form>
    </div>
  </div>
{% endblock extra_content %}

lists/templates/my_lists.html
{% extends "base.html" %}
{% block header_text %}My lists{% endblock %}
{% block list_form %}{% endblock list_form %}
{% block extra_content %}
  <div class="row">
    <div class="col-md-12">
    <h2>{{ owner.email }}'s lists</h2>
      <ul>
        {% for list in owner.list_set.all %}
          <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
      </ul>
    </div>
    {% if owner.shared_lists.all %}
    <div class="col-md-12">
    <h2>Shared with {{ owner.email }}</h2>
      <ul>
        {% for list in owner.shared_lists.all %}
          <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
            {% if list.owner %}( {{ list.owner.email }} ) {% endif %}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  </div>
{% endblock extra_content %}